version: '3.9'

services:

  backend:
    build:
      context: ./backend
    container_name: django_backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build:
      context: .
    container_name: react_frontend
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - backend

  db:
    image: postgres:17
    container_name: postgres_db
    restart: always

    environment:
      POSTGRES_DB: esgdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: