# Generated by Django 6.0.2 on 2026-02-06 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('DVA', 'Double Materiality Assessment'), ('IA', 'Initiative Analysis')], max_length=3)),
                ('text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('purpose', models.CharField(blank=True, choices=[('impact', 'Impact'), ('finansiel', 'Financial'), (None, 'N/A')], max_length=10, null=True)),
                ('dva_description', models.TextField(blank=True, help_text='Description for DVA questions')),
                ('typical_industries', models.TextField(blank=True)),
                ('topic', models.CharField(blank=True, help_text='e.g., Co2-udledninger. From iaQuestions.secondSubcategory', max_length=255)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('number', models.CharField(blank=True, help_text='Hierarchical number, e.g., 1.1.1', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['question_type', 'sub_category', 'number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(blank=True, help_text='Admin user linked to this company', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(help_text='The reporting year')),
                ('boolean_answer', models.BooleanField(blank=True, help_text='For DVA questions', null=True)),
                ('is_answered', models.BooleanField(default=False, help_text='For IA questions (i.e., is the initiative implemented?)')),
                ('metric_value', models.CharField(blank=True, help_text='Optional metric/value associated with an IA answer', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.company')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.question')),
            ],
            options={
                'ordering': ['-year', 'question'],
                'unique_together': {('company', 'question', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.answer')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=10, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_categories', to='core.category')),
            ],
            options={
                'verbose_name_plural': 'Sub-categories',
                'ordering': ['label'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='core.subcategory'),
        ),
    ]
