# Generated by Django 6.0.2 on 2026-02-12 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.CharField(blank=True, help_text='e.g., Co2-udledninger. From iaQuestions.secondSubcategory', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='CompanyBasismodulData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basis_for_preparation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Grundlag for udarbejdelse')),
                ('legal_form', models.CharField(blank=True, max_length=100, null=True, verbose_name='Virksomhedens juridiske form')),
                ('nace_sector_codes', models.JSONField(blank=True, default=list, null=True, verbose_name='NACE sektor kode(r)')),
                ('balance_sheet_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Balancesum')),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Omsætning')),
                ('employees', models.PositiveIntegerField(blank=True, null=True, verbose_name='Antal ansatte')),
                ('asset_locations', models.TextField(blank=True, null=True, verbose_name='Adresser og geolokation på væsentlige aktiver og anlæg')),
                ('confidentiality_exclusions', models.TextField(blank=True, null=True, verbose_name='Eventuelle udeladelser grundet fortrolighed')),
                ('esg_certificate_description', models.TextField(blank=True, null=True, verbose_name='Kort beskrivelse af din virksomheds eventuelle ESG-certifikat eller miljømærker')),
                ('has_initiatives', models.BooleanField(blank=True, null=True, verbose_name='Har konkrete indsatser, politikker eller initiativer for bæredygtighed')),
                ('electricity_renewable', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Elektricitet: Vedvarende')),
                ('electricity_non_renewable', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Elektricitet: Ikke-vedvarende')),
                ('fuel_renewable', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Brændstoffer: Vedvarende')),
                ('fuel_non_renewable', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Brændstoffer: Ikke-vedvarende')),
                ('scope1_emissions', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Scope 1 CO₂e udledninger')),
                ('scope2_emissions', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Scope 2 CO₂e udledninger')),
                ('co2e_intensity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='CO₂e-intensitet')),
                ('scope3_emissions', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Scope 3 CO₂e udledninger (valgfri)')),
                ('pollution_reporting', models.TextField(blank=True, null=True, verbose_name='Rapportering om forurening')),
                ('biodiversity_sensitive_areas', models.TextField(blank=True, null=True, verbose_name='Områder i nærheden af biodiversitetsfølsomme områder')),
                ('land_area_usage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Virksomhedens arealforbrug (valgfri)')),
                ('water_withdrawal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Udtagning af vand')),
                ('water_consumption', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Vandforbrug (valgfri)')),
                ('uses_circular_economy_principles', models.BooleanField(blank=True, null=True, verbose_name='Anvender principper fra cirkulær økonomi')),
                ('circular_economy_description', models.TextField(blank=True, null=True, verbose_name='Beskrivelse af arbejde med cirkulær økonomi')),
                ('total_waste_hazardous', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total mængde farligt affald årligt')),
                ('total_waste_non_hazardous', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total mængde ikke-farligt affald årligt')),
                ('waste_recycled', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total mængde affald sendt til genbrug/genanvendelse')),
                ('mass_flow_materials', models.TextField(blank=True, null=True, verbose_name='Årlige masse-flow for centrale materialer (valgfri)')),
                ('contract_type', models.TextField(blank=True, null=True, verbose_name='Kontrakttype')),
                ('gender_composition', models.TextField(blank=True, null=True, verbose_name='Kønssammensætning')),
                ('employees_abroad', models.TextField(blank=True, null=True, verbose_name='Ansættelseskontrakter i andre lande udover Danmark (valgfri)')),
                ('employee_turnover', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Medarbejderomsætning (valgfri)')),
                ('work_accidents', models.PositiveIntegerField(blank=True, null=True, verbose_name='Registrerede arbejdsulykker')),
                ('work_related_deaths', models.PositiveIntegerField(blank=True, null=True, verbose_name='Arbejdsrelaterede dødsfald')),
                ('salary_below_minimum', models.CharField(blank=True, max_length=50, null=True, verbose_name='Aflønning over/under minimumsløn')),
                ('gender_pay_gap', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Lønforskel mellem mandlige og kvindelige ansatte (valgfri)')),
                ('collective_bargaining_coverage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Procentvis ansatte dækket af kollektiv overenskomst')),
                ('avg_training_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Uddannelsestimer i gennemsnit pr. ansat')),
                ('corruption_bribery_cases', models.PositiveIntegerField(blank=True, null=True, verbose_name='Antal domme og bøder i relation til korruption & bestikkelse (valgfri)')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basismodul_data', to='core.company')),
            ],
            options={
                'verbose_name': 'Company Basismodul Data',
                'verbose_name_plural': 'Company Basismodul Data',
            },
        ),
    ]
