# Generated by Django 6.0.2 on 2026-02-13 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_question_topic_companybasismoduldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybasismoduldata',
            name='year',
            field=models.PositiveIntegerField(default=2026, help_text='The reporting year for this Basismodul data.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companybasismoduldata',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basismodul_data', to='core.company'),
        ),
        migrations.AlterUniqueTogether(
            name='companybasismoduldata',
            unique_together={('company', 'year')},
        ),
    ]
