# Generated by Django 6.0.2 on 2026-02-13 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_companybasismoduldata_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyExtendedModuleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(help_text='The reporting year for this Extended Module data.')),
                ('products_services_groups', models.TextField(blank=True, null=True, verbose_name='Væsentlige grupper af produkter og/eller tjenesteydelser')),
                ('markets', models.TextField(blank=True, null=True, verbose_name='Væsentlige markeder')),
                ('business_relations', models.TextField(blank=True, null=True, verbose_name='Primære forretningsforbindelser')),
                ('strategy_sustainability_elements', models.TextField(blank=True, null=True, verbose_name='Centrale elementer fra virksomhedens strategi, der er relateret til/påvirker bæredygtighedsspørgsmål (C1)')),
                ('existing_practices_policies', models.TextField(blank=True, null=True, verbose_name='Beskrivelse af eksisterende praksisser/politikker/handlinger (C2)')),
                ('future_initiatives_targets', models.TextField(blank=True, null=True, verbose_name='Beskrivelse af fremtidige initiativer/målsætninger (C2)')),
                ('highest_management_level', models.CharField(blank=True, max_length=255, null=True, verbose_name='Angivelse af højeste ledelsesniveau i virksomheden, der er ansvarlig for implementering (C2)')),
                ('scope3_co2e_relevant', models.BooleanField(blank=True, null=True, verbose_name='Vurdér, om Scope 3 CO₂e-udledning er relevant')),
                ('scope3_co2e_emissions', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Scope 3 CO₂e-udledninger')),
                ('co2e_reduction_target', models.TextField(blank=True, null=True, verbose_name='CO₂e-reduktionsmål (C3)')),
                ('co2e_baseline_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='CO₂e-udledning i baselineår (C3)')),
                ('co2e_reduction_actions', models.TextField(blank=True, null=True, verbose_name='Liste med de handlinger, der skal bidrage til at nå CO₂e-reduktionsmålene (C3)')),
                ('climate_transition_plan', models.TextField(blank=True, null=True, verbose_name='Omstillingsplan for modvirkning af klimaforandringer (C3)')),
                ('climate_risks_description', models.TextField(blank=True, null=True, verbose_name='Beskrivelse af klimarelaterede risici og/eller klimarelaterede omstillingsrisici (C4)')),
                ('exposure_vulnerability', models.TextField(blank=True, null=True, verbose_name='Eksponering og sårbarhed for virksomhedens aktiver, aktiviteter og værdikæde (C4)')),
                ('climate_risks_time_horizon', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tidshorisont for, hvornår de klimarelaterede risici og omstillingsrisici forventes at få negativ indflydelse på virksomheden (C4)')),
                ('climate_adaptation', models.BooleanField(blank=True, null=True, verbose_name='Oplysning om klimatilpasning (JA/NEJ) (C4)')),
                ('financial_impact_climate_risks', models.TextField(blank=True, null=True, verbose_name='Potentiel negativ påvirkning på virksomhedens finansielle præstation og forretningsdrift fra de oplistede klimarisici (valgfri)')),
                ('gender_management_ratio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Forholdet mellem kvinder og mænd på ledelsesniveau (C5)')),
                ('independent_workers', models.PositiveIntegerField(blank=True, null=True, verbose_name='Antal selvstændige, som arbejder for din virksomhed (C5)')),
                ('temporary_workers', models.PositiveIntegerField(blank=True, null=True, verbose_name='Antal vikarer, som arbejder for din virksomhed (C5)')),
                ('code_of_conduct_hr_policy', models.BooleanField(blank=True, null=True, verbose_name='Oplysning om ”code of conduct” eller menneskerettighedspolitik for din virksomheds egen arbejdsstyrke (JA/NEJ) (C6)')),
                ('grievance_mechanism', models.BooleanField(blank=True, null=True, verbose_name='Oplysning om klagemekanisme for virksomhedens egne ansatte (JA/NEJ) (C6)')),
                ('confirmed_hr_incidents_own_workforce', models.TextField(blank=True, null=True, verbose_name='Bekræftede negative menneskerettighedshændelser for din virksomheds egen arbejdsstyrke (C7)')),
                ('confirmed_hr_incidents_value_chain', models.TextField(blank=True, null=True, verbose_name='Bekræftede negative menneskerettighedshændelser i din virksomheds værdikæde (C7)')),
                ('revenue_selected_sectors', models.TextField(blank=True, null=True, verbose_name='Indtægter fra udvalgte sektorer (C8)')),
                ('eu_benchmarks_exceedance', models.BooleanField(blank=True, null=True, verbose_name='Overskridelse af EU-benchmarks i overensstemmelse med Parisaftalen (C8)')),
                ('gender_top_management_ratio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Forholdet mellem kvinder og mænd i det øverste ledelsesorgan (C9)')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extended_module_data', to='core.company')),
            ],
            options={
                'verbose_name': 'Company Extended Module Data',
                'verbose_name_plural': 'Company Extended Module Data',
                'unique_together': {('company', 'year')},
            },
        ),
    ]
