# Generated by Django 6.0.2 on 2026-02-19 09:21

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_companyextendedmoduledata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.RemoveField(
            model_name='companybasismoduldata',
            name='basis_for_preparation',
        ),
        migrations.RemoveField(
            model_name='document',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
        migrations.AddField(
            model_name='answer',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='answers', to='core.document'),
        ),
        migrations.AddField(
            model_name='document',
            name='admin_comment',
            field=models.TextField(blank=True, help_text='Admin feedback if status is incomplete', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.company'),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'Ikke-tjekket'), ('incomplete', 'Mangelfuldt'), ('approved', 'Godkendt')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='topic',
            field=models.CharField(blank=True, help_text='e.g., 1.1 CO2 udledninger', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='year',
            field=models.PositiveIntegerField(blank=True, help_text='The reporting year', null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/%Y/%m/%d/', validators=[core.validators.validate_file_security]),
        ),
    ]
